# Configuration for librarian-puppet. For example:
#
forge 'https://forgeapi.puppetlabs.com'
#
# mod 'puppetlabs/razor'
# mod 'puppetlabs/ntp', '0.0.3'
#
# mod 'apt',
#   :git => 'git://github.com/puppetlabs/puppetlabs-apt.git'
#
# mod 'stdlib',
#   :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

# Configuration begins here
forge 'http://forge.puppetlabs.com'

# Installs the ZSH and plugin set
mod 'acme/ohmyzsh'

# Adding TMUX
mod 'zanloy/tmux'

mod 'puppetlabs/stdlib'

# Adding Node JS (Later Version)
mod 'maestrodev/wget'
mod 'willdurand/nodejs'
