# Configuration for librarian-puppet. For example:
#
# forge 'http://forge.puppetlabs.com'
#
# mod 'puppetlabs/razor'
# mod 'puppetlabs/ntp', '0.0.3'
#
# mod 'apt',
#   :git => 'git://github.com/puppetlabs/puppetlabs-apt.git'
#
# mod 'stdlib',
#   :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

# Configuration begins here
forge 'http://forge.puppetlabs.com'

# Installs the ZSH and plugin set
mod 'acme/ohmyzsh'

# Adds github host to known hosts
mod 'inkblot/github'

# Setting up RVM
mod 'maestrodev/rvm'
